### ISSUE TITLE
Evaluate Bug?

### ISSUE THREAD

**Issue by sylcito** [Traffic-X/MonoLSS#1]
Hi bro,

Great job, I just noticed it and can't wait to try it! But I've run into a problem:

https://github.com/Traffic-X/MonoLSS/blob/9cbff83cb25a4bbd80e2d2c1f9412357015fb375/tools/eval.py#L1278C9-L1278C85

Predictions have one less `score` item than labels. maybe [:, :-1] can delete?

**Comment by zhenjiaa** [comment]
fixed
