### ISSUE TITLE
FileNotFoundError: kitti/training/label_2/007481.txt not found.

### ISSUE THREAD

**Issue by weiyunsong** [Traffic-X/MonoLSS#11]
Hello, may I ask why the label_2 information is still needed in test mode? Does the code need to be changed in the test case?
FileNotFoundError: kitti/training/label_2/007481.txt not found.

**Comment by HyperbolicCurve** [comment]
Hi, I also encountered this problem FileNotFoundError: kitti/training/label_2/007481.txt not found, how can I solve it? @weiyunsong

**Comment by 917731216** [comment]
> 嗨，我也遇到了这个问题FileNotFoundError：找不到kitti/training/label_2/007481.txt，我该如何解决？

请问你解决这个问题了吗

**Comment by jjrCN** [comment]
In test mode, this problem is not need to be solve, the results has be generated. you can upload to kitti web to test your result
