### ISSUE TITLE
Training with Waymo Dataset

### ISSUE THREAD

**Issue by floriangue** [Traffic-X/MonoLSS#12]
Hello, thank you for your great work and for releasing your code.
As you also have trained MonoLSS on Waymo dataset: Would you mind sharing the config setup and the dataset class for performing experiments on Waymo dataset? Thanks a lot!

**Comment by jjrCN** [comment]
Sorry it's a bit long ago, you can first refer to other papers (such as DEVIANT) to convert Waymo to KITTI, and then use MonoLSS for training
