### ISSUE TITLE
Questions about using the BN layer

### ISSUE THREAD

**Issue by Puiching-Memory** [Traffic-X/MonoLSS#13]
Monolss's 3D detector heads output offset,size and heading,
There is an additional BatchNorm2d layer compared to MonoDle.

In my experiments, using the BN layer reduced the number of parameters a bit, but it also resulted in a slight drop in accuracy.

I wonder what the design here was for.
Thanks!

**Comment by jjrCN** [comment]
MonoLSS does not add BatchNorm2d additionally, this part refers to GUPNet
