### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by ALPHASOV** [Traffic-X/MonoLSS#14]
大佬好（我想请问一下为什么这里还要做2D检测，SMOKE模型说2D检测除了引入噪声什么用都没有，我个人来努力的理解这个新模型也觉得LSS的对于3D的预测的中心位置偏移预测也是独立于2D预测的，那请问在LSS中2D检测到底起什么作用来着（谢谢大佬

**Comment by jjrCN** [comment]
2D检测对3D检测的作用是一个值得研究的学术问题，不同文章对此都有不同的看法。我记得MonoDLE中反驳了SMOKE的观点，你可以进一步深入研究一下。
