### ISSUE TITLE
请问一下这个测试集跑出来的成绩是怎么计算的May I ask how the score of this test set is calculated

### ISSUE THREAD

**Issue by 7945jiao** [Traffic-X/MonoLSS#15]
比如这个AP3D的26.11 19.15 16.94是怎么得出来的
For example, how did this AP3D 26.11 19.15 16.94 come out
<img width="602" alt="屏幕截图 2024-08-06 144923" src="https://github.com/user-attachments/assets/f7fd91d8-65cc-41fe-a780-a3aeb7c5b492">

**Comment by 7945jiao** [comment]
这个26.11的具体意义是什么What is the specific meaning of this 26.11

**Comment by jjrCN** [comment]
请参考KITTI官方评测方法
