### ISSUE TITLE
How to preprocess Kitti data

### ISSUE THREAD

**Issue by penghujin** [Traffic-X/MonoLSS#17]

**Comment by jjrCN** [comment]
There is no additional preprocessing, the data format has been supplemented in the readme

**Comment by penghujin** [comment]
前辈您好，我现在在复现您这个monolss项目，我确保数据集配置完全正常我执行python tools/train_val.py
-t结果不到百分之一是为什么，我尝试复现您的项目已数月，此问题困扰我已久，若您能指点一二我将不胜感激

jjrCN ***@***.***>于2024年9月19日 周四19:01写道：

**Comment by jjrCN** [comment]
-t 是在测试集上推理，然后将结果压缩上传到kitti官方评测

1、先用我们提供的权重推理，得到结果一共7519个txt
2、打包zip，使用以下命令打包
cd outputs/data
zip -r submission.zip .
3、上传kitti官方
严格执行这个过程，测试结果应该和我们公布的测试结果相同

之后再定位是不是训练时有问题导致精度不对。

**Comment by penghujin** [comment]
好的谢谢您的指导，还想请教一下您怎么跑出验证集的结果

jjrCN ***@***.***>于2024年9月26日 周四18:09写道：

**Comment by jjrCN** [comment]
验证集结果会在训练时边训边评。具体参看kitti.yaml中的配置参数，eval_start和eval_frequeny

**Comment by penghujin** [comment]
jjrCN ***@***.***>于2024年9月26日 周四18:52写道：

**Comment by penghujin** [comment]
这是我们-e的结果

jjrCN ***@***.***>于2024年9月26日 周四18:52写道：

**Comment by penghujin** [comment]
感谢前辈指导，这个tabel5百分之二十多的结果是怎么跑出来的啊，我们跑出来的结果要么是0.多要么就是百分之九十多，没有跑出过百分之二三十的数值

jjrCN ***@***.***>于2024年9月26日 周四18:52写道：

**Comment by jjrCN** [comment]
我看不到你的结果，但代码逻辑其实不难，从main.py入手，会根据不同的args（-t或-e）调用不同的dataloader并执行相应推理，你可以再仔细看下代码。
90多的结果有可能是你用了trainval set训出的模型来评测验证集。

**Comment by penghujin** [comment]
我们用的是您在网站放的那个模型 可以加下您微信向您请教吗，我们复现您的这个项目几个月了，很想解决这个问题

jjrCN ***@***.***>于2024年9月26日 周四19:18写道：

**Comment by penghujin** [comment]
您好，如果我想对您的模型进行复现，一定要上传到kitti官网才能看到复现是否成功吗，我能否达到您论文上验证集的效果

jjrCN ***@***.***>于2024年9月26日 周四19:18写道：

**Comment by penghujin** [comment]
老师您好
，在您的指导下我们终于得到了正常的数据，但我们训练出来的模型执行推理结果上传在kitti官网数据比您提供的模型少了几个点想问一下这是什么原因，是不是要更改学习率还是测试的服务器环境等和您不同

胡劲 ***@***.***>于2024年9月29日 周日12:55写道：
