### ISSUE TITLE
problems when running "tools/train_val.py -t"

### ISSUE THREAD

**Issue by CuiLily** [Traffic-X/MonoLSS#3]
Thank you for your excellent work and sharing!

When I tried to run '**python tools/train_val.py -t**', I encountered the following error. It seems that the code is attempting to evaluate using the 'test set', but the 'test set' does not have labels. Do I need to make relevant modifications in the '**kitti.yaml**' file?

![1280X1280](https://github.com/Traffic-X/MonoLSS/assets/55568903/3b3cc045-126a-4e00-8b85-80c64440f45d)

**Comment by jjrCN** [comment]
Hello, the test set results need to be uploaded to kitti official website for testing.
