### ISSUE TITLE
Clarification of the approach

### ISSUE THREAD

**Issue by johannes-tum** [Traffic-X/MonoLSS#6]
Thank you very much for your approach! 
- As far as we understand your approach only needs intrinsics and the image during test time. 
- During training time we always thought you are only using: category, 2d center, 2d dimension, 3d dimension, 3d location, intrinsics, rotation angle. 

But since your approach is based on DID-M3D it seems as if you also use depth maps as input during training time. Is that correct? Anything else you use during training or test time that we may have overlooked?

You also perform experiments on Waymo and NuScenes. Is it possible that you also provide the code and command line commands for these datasets?

**Comment by jjrCN** [comment]
Monolss does not use depth maps during training time or testing time, no extra data is used either.
