### ISSUE TITLE
Can the Mixup3D strategy be applied to monocular 3D object detection models that use additional depth?

### ISSUE THREAD

**Issue by aqr1961** [Traffic-X/MonoLSS#8]
The Mixup3D strategy has brought about a significant improvement in performance. I would like to know if this strategy can be applied to object detection models that use additional depth, such as DID-M3D. If so, when mixing dense depth pixels proportionally, would it cause depth ambiguity?

**Comment by jjrCN** [comment]
It feels ambiguous. The reason why the obstacle-level depth mixup can be understood as unambiguous is that the obstacle can be regarded as a semantic whole, but the dense pixel-level mixup cannot be understood in this way. One pixel will correspond to two depths, which will bring ambiguity.
